### ISSUE TITLE
AttributeError: 'Zerodha' object has no attribute 'ticker'

### ISSUE THREAD

**Issue by crazylala** [jugaad-py/jugaad-trader#17]
from jugaad_trader import Zerodha
import logging
from jugaad_trader import Zerodha

kite = Zerodha()

# Set access token loads the stored session.
# Name chosen to keep it compatible with kiteconnect.
kite.set_access_token()

kws = kite.ticker()

Error:

    kws = kite.ticker()
AttributeError: 'Zerodha' object has no attribute 'ticker'

**Comment by sevakram** [comment]
Can you please run `pip install --upgrade jugaad-trader` 

This feature was added in recent versions

**Comment by crazylala** [comment]
Thanks working perfectly now
