### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by hemangbhavasar** [jugaad-py/jugaad-trader#2]
ERROR: Could not find a version that satisfies the requirement jugad-trader (from versions: none)
ERROR: No matching distribution found for jugad-trader

**Comment by ghost** [comment]
What was the action performed? If I understand you were trying to install jugaad-trader?
Are you using python 3 or 2
Can you please share the complete error?

**Comment by ghost** [comment]
I think you tried to install using pip, there was a spelling mistake in the documentation.

Please try - pip install jugaad-trader

**Comment by hemangbhavasar** [comment]
still getting error " ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."

**Comment by sasi143** [comment]
@hemangbhavasar, try below command:

pip install git+https://github.com/jugaad-py/jugaad-trader.git

**Comment by ghost** [comment]
can you try now please? with latest version

**Comment by hemangbhavasar** [comment]
Ok, let me try

**Comment by ghost** [comment]
closing the issue, as it should work with latest updates.

Please re-open the issue if it happens again.
