### ISSUE TITLE
After creating a position, when we check positions multiple times "unrealised" (unrealised profit) is not updated in the return value.

### ISSUE THREAD

**Issue by nobody31985** [jugaad-py/jugaad-trader#27]
Thanks for your code. Its very useful.

After creating a position, when we check positions multiple times after price change,  "unrealised" (unrealised profit) is not updated in the return value.
url = "https://kite.zerodha.com/oms/portfolio/positions"

Also after closing a position realised profit = 0, in return value.

**Comment by sevakram** [comment]
Ok, I don't think Jugaad can do anything about it, its just a messenger, but here is what you can check and help community

1. Open developer tools in chrome and look at the json response which you get when you go to positions page and confirm if its different than what you are getting using jugaad

2. Position values might get updated using Websockets, I couldn't find any documentation on this, so if its Websockets, you'll have reverse engineer their request response, Websocket requests also can be seen in developer tools

**Comment by nobody31985** [comment]
The json response is {"status":"success","data":{"net": [], "day": []}}, which is same in browser and the request.get.

I added "cache-control: no-cache"  in request header also, but still values are not updated.

The response is getting updated only once in 15 min for POSITIONS and HOLDINGS, guess related to MAX AGE.
I know basics of python, dont know JS. So not sure how the dynamin PNL and unrealised profit is getting updated in browser and not in request response.

I will try websockets, and see if any.
