### ISSUE TITLE
public_token not found

### ISSUE THREAD

**Issue by sasi143** [jugaad-py/jugaad-trader#3]
@jugaader , really kudos to your work......tremendous effort.

I have found one minor issue:
 
**"self.public_token = j['data']['public_token']"**, from zerodha.py file, line number 94 getting issue.

Just comment the line, then it is working fabulously

**Comment by ghost** [comment]
Thanks for using the library @sasi143 

I've commented it. I've made other changes as well, so it'll be mostly compatible with KiteConnect.
