### ISSUE TITLE
pip install not adding files with latest changes

### ISSUE THREAD

**Issue by kool4u** [jugaad-py/jugaad-trader#30]
Jugaad trader lib does not show latest changes available in the code.
I tried upgrading jugaad-trader, even I uninstalled it and installed it again using pip but still latest code is not showing up in the  lib. 

Can anyone please help me here.

**Comment by kool4u** [comment]
@sevakram  Can you please check this query.

**Comment by akashAD98** [comment]
im also facing the same issue.
when i did pip show jugaad-trader ,its showing package is installed, but when i ran script its not working
im getting this issue

(algo) E:\Share Market\ALGO TRADING\Training_Algo\akash\jugad_trader>py download_data.py
Traceback (most recent call last):
  File "download_data.py", line 1, in <module>
    from jugaad_trader import Zerodha
ModuleNotFoundError: No module named 'jugaad_trader'

**Comment by PrajwalShenoy** [comment]
The issue might be due to the package not being updated in pypi
I am using `pip install git+https://github.com/jugaad-py/jugaad-trader.git` with `kiteconnect==4.1.0` havent faced any issues so far

**Comment by sevakram** [comment]
Closing this issue, This should be resolved with latest version
