### ISSUE TITLE
kite.quote/ltp not working

### ISSUE THREAD

**Issue by kiriace** [jugaad-py/jugaad-trader#36]
kite.quote(["NSE:INFY", "BSE:INFY"])

D:\anaconda3\lib\site-packages\kiteconnect\connect.py in quote(self, *instruments)
    564             ins = instruments[0]
    565 
--> 566         data = self._get("market.quote", {"i": ins})
    567         return {key: self._format_response(data[key]) for key in data}
    568 

D:\anaconda3\lib\site-packages\kiteconnect\connect.py in _get(self, route, params)
    815     def _get(self, route, params=None):
    816         """Alias for sending a GET request."""
--> 817         return self._request(route, "GET", params)
    818 
    819     def _post(self, route, params=None):

D:\anaconda3\lib\site-packages\jugaad_trader\zerodha.py in _request(self, route, method, url_args, params, is_json, query_params)
    174 
    175                 # native Kite errors
--> 176                 exp = getattr(ex, data.get("error_type"), ex.GeneralException)
    177                 raise exp(data["message"], code=r.status_code)
    178 

TypeError: getattr(): attribute name must be string

**Comment by csatoskar** [comment]
Following error coming while running !pip install jugaad-trader ..plz suggest...tnx
Error: The login session has expired or doesn't exist. Please try again.

**Comment by sbrahmam** [comment]
I am also facing same issue since today's morning. Changed accounts, delete files in "AppData" Folder. But no use. Seems something at Broker's end changed.

**Comment by csatoskar** [comment]
> I am also facing same issue since today's morning. Changed accounts, delete files in "AppData" Folder. But no use. Seems something at Broker's end changed.

hey bro if u have u got any solutions plz do let me know..thanks

**Comment by ssheikh098** [comment]
were you able to resolve this issue?

**Comment by ashishanand7** [comment]
@iamknownstranger Since you did the last commit. Can you comment on this. This quote and ltp is not working anymore.
 Facing same TypeError "getattr(): attribute name must be string"

**Comment by ashishanand7** [comment]
Upgrade kiteconnect to fix this
