### ISSUE TITLE
login problem 

### ISSUE THREAD

**Issue by csatoskar** [jugaad-py/jugaad-trader#37]
:Following error coming while running !pip install jugaad-trader ..plz suggest...tnx 
Error: The login session has expired or doesn't exist. Please try again.

**Error**
Error log

**Additional context**
![jtrader login problem](https://user-images.githubusercontent.com/40542248/148512930-d1f9553f-d5d9-4009-8fcd-4a99be0bcc2c.JPG)

**Comment by sevakram** [comment]
This might be transient issue. Please re-open if this persists.
