### ISSUE TITLE
Session is expiring frequently 

### ISSUE THREAD

**Issue by sasi143** [jugaad-py/jugaad-trader#4]
@jugaader  No words to your work, just simply awesome.

I am using the Zerodha account.

I have some minor issues, Every time session is ending after a couple of minutes in Zerodha API.  Is there any way that we can specify the timeout to expire or without the session expire?

**Comment by sasi143** [comment]
@jugaader Is there any better approach that we can re-login automatically when the connection lost

**Comment by ghost** [comment]
@sasi143  Thanks for appreciation

Are you logging in from your browser in between because it will end your session.

Is it possible to share some code snippets so that I can replicate/observe?

**Comment by sasi143** [comment]
@jugaader Thanks for replying back, I am not logging in the browser in between but still session is expiring.

If you don't mind could you please share your e-mail address, so that I can share the code with you

**Comment by sasi143** [comment]
@jugaader Here is the timeout error I am getting frequently

`
timeout                                   Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    425                     # Otherwise it looks like a bug in the code.
--> 426                     six.raise_from(e, None)
    427         except (SocketTimeout, BaseSSLError, SocketError) as e:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\packages\six.py in raise_from(value, from_value)

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    420                 try:
--> 421                     httplib_response = conn.getresponse()
    422                 except BaseException as e:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\http\client.py in getresponse(self)
   1331             try:
-> 1332                 response.begin()
   1333             except ConnectionError:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\http\client.py in begin(self)
    302         while True:
--> 303             version, status, reason = self._read_status()
    304             if status != CONTINUE:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\http\client.py in _read_status(self)
    263     def _read_status(self):
--> 264         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    265         if len(line) > _MAXLINE:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\socket.py in readinto(self, b)
    668             try:
--> 669                 return self._sock.recv_into(b)
    670             except timeout:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\ssl.py in recv_into(self, buffer, nbytes, flags)
   1240                   self.__class__)
-> 1241             return self.read(nbytes, buffer)
   1242         else:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\ssl.py in read(self, len, buffer)
   1098             if buffer is not None:
-> 1099                 return self._sslobj.read(len, buffer)
   1100             else:

timeout: The read operation timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError                          Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    723 
--> 724             retries = retries.increment(
    725                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    402             if read is False or not self._is_method_retryable(method):
--> 403                 raise six.reraise(type(error), error, _stacktrace)
    404             elif read is not None:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\packages\six.py in reraise(tp, value, tb)
    734                 raise value.with_traceback(tb)
--> 735             raise value
    736         finally:

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    669             # Make the request on the httplib connection object.
--> 670             httplib_response = self._make_request(
    671                 conn,

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    427         except (SocketTimeout, BaseSSLError, SocketError) as e:
--> 428             self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    429             raise

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\urllib3\connectionpool.py in _raise_timeout(self, err, url, timeout_value)
    334         if isinstance(err, SocketTimeout):
--> 335             raise ReadTimeoutError(
    336                 self, url, "Read timed out. (read timeout=%s)" % timeout_value

ReadTimeoutError: HTTPSConnectionPool(host='kite.zerodha.com', port=443): Read timed out. (read timeout=7)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
<ipython-input-44-de89d6471009> in <module>
----> 1 z.ltp("NSE:INFY")

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\kiteconnect\connect.py in ltp(self, *instruments)
    593             ins = instruments[0]
    594 
--> 595         return self._get("market.quote.ltp", {"i": ins})
    596 
    597     # def instruments_margins(self, segment):

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\kiteconnect\connect.py in _get(self, route, params)
    815     def _get(self, route, params=None):
    816         """Alias for sending a GET request."""
--> 817         return self._request(route, "GET", params)
    818 
    819     def _post(self, route, params=None):

<ipython-input-36-4a2e858c9b71> in _request(self, route, method, parameters)
     96         # Any requests lib related exceptions are raised here - http://docs.python-requests.org/en/master/_modules/requests/exceptions/
     97         except Exception as e:
---> 98             raise e
     99 
    100         if self.debug:

<ipython-input-36-4a2e858c9b71> in _request(self, route, method, parameters)
     84 
     85         try:
---> 86             r = self.reqsession.request(method,
     87                                         url,
     88                                         data=params if method in ["POST", "PUT"] else None,

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

~\AppData\Local\Continuum\anaconda3\envs\trading\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    527                 raise SSLError(e, request=request)
    528             elif isinstance(e, ReadTimeoutError):
--> 529                 raise ReadTimeout(e, request=request)
    530             else:
    531                 raise

ReadTimeout: HTTPSConnectionPool(host='kite.zerodha.com', port=443): Read timed out. (read timeout=7)

​
`

**Comment by ghost** [comment]
How frequently are you querying it. Is it in a loop?

**Comment by sasi143** [comment]
If I am continuously querying, problem is not occurring. But, when I am querying after some time period like more than 5 min, then this error is getting

**Comment by sevakram** [comment]
I believe this behavior is consistent with browser as expected, Kite's website always has a websocket open which might help in keeping the session open for longer.

So current workaround is to query it every couple of minutes.

For now, I'm closing the issue. Please open if you have other findings.
