### ISSUE TITLE
2FA  TOTP 

### ISSUE THREAD

**Issue by Santunav** [jugaad-py/jugaad-trader#45]
**Describe the bug**
Hi,

I'm using this API since a month. Just started developing Algo. Now Zerodha mandating 2FA TOTP.  
Will there be any enhancement to support ?

**Comment by ssheikh098** [comment]
Hi @Santunav ,

I used pyotp package and added few lines of code in zcli.py, not sure if anyone will extend this package as last it was updated 13 months back.

![image](https://user-images.githubusercontent.com/14261211/185045817-5b382936-9d6e-4a1c-aacc-4f365f26c2e5.png)

replaced this code with - for now i just hardcoded my TOTP secret in the code but i need to move this from code in future. 

![image](https://user-images.githubusercontent.com/14261211/185045932-ce64935d-a756-4dc5-ba18-0a4458333d61.png)

**Comment by Santunav** [comment]
Hi @ssheikh098 
Thank you for the response. I doubt if the maintainer is still actively contributing. 
can you paste "startsession" function with dummy  your TOTP secret. 
I will try to integrate . 

Thanks  in advance 
Santunav

**Comment by ssheikh098** [comment]
@Santunav 

I have copied the session code from master package and placed the PYOTP code for your reference.

Import 3 packages

import pyotp
import time
import datetime

I placed random string from google for PYOTP for your reference. You need to copy this from your zerodha trading platform under profile section. 
@zerodha.command()

def startsession():
    """Saves your login session in the app config folder"""

    user_id = click.prompt("User ID >")
    password = click.prompt("Password >", hide_input=True)
    z = Zerodha()
    z.user_id = user_id
    z.password = password
    j = z.login_step1()
    if j['status'] == 'error':
        click.echo(click.style("Error: {}".format(j['message']), fg="red"))
        return
    #z.twofa = click.prompt("Pin >", hide_input=True)
    authkey = pyotp.TOTP('S5IDP8INCIGWCZ6KJH8X20H97UB4OKGJ')
    z.twofa = authkey.now()
    time_remaining = authkey.interval - datetime.datetime.now().timestamp() % authkey.interval
    if time_remaining <= 5.0:
        print("pending less than 5 seconds.. regenerate")
        time.sleep(6)
        z.twofa = authkey.now()
    j = z.login_step2(j)
    if j['status'] == 'error':
        click.echo(click.style("Error: {}".format(j['message']), fg="red"))
        return
    z.enc_token = z.r.cookies['enctoken']
    p = z.profile()

    click.echo(click.style("Logged in successfully as {}".format(p['user_name']), fg='green'))
    with open(os.path.join(app_dir, session_file), "wb") as fp:
        pickle.dump(z.reqsession, fp)
    click.echo("Saved session successfully")

**Comment by Santunav** [comment]
Hi @ssheikh098 
Thanks a lot, I' am not using both web and algo together . This code is fine to me.  
If you wish to share full code to use both web and algo together just for ref to other. 

Thanks 
Santunav
