### ISSUE TITLE
Updated code is not packaged to pypi

### ISSUE THREAD

**Issue by PrajwalShenoy** [jugaad-py/jugaad-trader#46]
**Describe the issue**
When code is updated in the `main`/`master` branch it is not being packaged and update din pypi. This is causing a lot of errors, especially if `kiteconnect` is updated to the latest version.

**Error**
TypeError: _request() got an unexpected keyword argument 'url args'

**Proposed solution**
* Create tags for major version of `jugad-trader`, that way people can choose the version that works best for them (Similar to how numpy versions can be downloaded.)
* Create github action to acutomatically update pypi with the lates package (I can help in setting this up)

**Comment by sevakram** [comment]
I have created github actions for build and publish now. Thanks for the suggestions.
