### ISSUE TITLE
DataException   

### ISSUE THREAD

**Issue by csatoskar** [jugaad-py/jugaad-trader#49]
DataException                             Traceback (most recent call last)
[<ipython-input-5-f2a6278dbf08>](https://localhost:8080/#) in <module>
     70   sr='NFO:NIFTY22'+exp+ str(int(n['atmn'][i])) +'PE'
     71   get_data = kite.historical_data(kite.ltp(sr)[sr]['instrument_token'],dates.strftime('%Y-%m-%d'),
---> 72                                 datee.strftime('%Y-%m-%d'), '15minute',)
     73   try:
     74     nd1=(pd.DataFrame(get_data))['close'][i]

2 frames
[/usr/local/lib/python3.7/dist-packages/jugaad_trader/zerodha.py](https://localhost:8080/#) in _request(self, route, method, parameters)
    194             raise ex.DataException("Unknown Content-Type ({content_type}) with response: ({content})".format(
    195                 content_type=r.headers["content-type"],
--> 196                 content=r.content))
    197 
    198     def get_chunk_js(self):

DataException: Unknown Content-Type (text/html; charset=UTF-8) with response: (b'<!DOCTYPE html>\n<html lang="en-US">\n<head>\n    <title>Just a moment...</title>\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=Edge">\n    <meta name="robots" content="noindex,nofollow">\n    <meta name="viewport" content="width=device-width,initial-scale=1">\n    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">\n    \n\n</head>\n<body class="no-js">\n    <div class="main-wrapper" role="main">\n    <div class="main-content">\n        <h1 class="zone-name-title h1">\n            <img class="heading-favicon" src="/favicon.ico"\n                 onerror="this.onerror=null;this.parentNode.removeChild(this)">\n            kite.zerodha.com\n        </h1>\n        <h2 class="h2" id="challenge-running">\n            Checking if the site connection is secure\n        </h2>\n        <noscript>\n            <div id="challenge-error-title">\n                <div class="h2">\n                    <span class="icon-wrapper">\n                        <div class="heading-icon warning-icon"></div>\n                    </span>\n                    <span id="challenge-error-text">\n                        Enable JavaScript and cookies to continue\n                    </span>\n                </div>\n            </div>\n        </noscript>\n        <div id="trk_jschal_js" style="display:none;background-image:url...

**Comment by sevakram** [comment]
Closing issue for cleanup, please report again if issue persists
