### ISSUE TITLE
[Feature] How can I add the kite.order_margins function?

### ISSUE THREAD

**Issue by akshatc12** [jugaad-py/jugaad-trader#50]
I can see the api endpoint being discussed in the official forums, however I can't seem to figure out how I can add another function.

For that matter, where are the other functions saved in the scripts? Or are they not explicitly defined? Because, if I could see them, I could contribute more similar to them.

**Comment by ssheikh098** [comment]
@BruceWayne1219 whoever wrote this package has utilized all the standard package for end point call. can you not just call below function as kite.margin() or kite.order_margins()...

![image](https://user-images.githubusercontent.com/14261211/213318815-25511b9d-fc15-4626-80c9-fe3aee5a3649.png)


![image](https://user-images.githubusercontent.com/14261211/213318468-46593d8b-392b-4093-aa19-4c0f11ee92be.png)


![image](https://user-images.githubusercontent.com/14261211/213318301-4623a9c3-83c6-4af8-8524-ea0688b48026.png)

**Comment by akshatc12** [comment]
The order_margins function doesn't exist. Maybe I need to update?

Also, where are your screenshot from? They seem to be from the script I am
looking for.

**Comment by ssheikh098** [comment]
It should be part of standard Kite package. I hope you have latest Kite package. As i said earlier, the developer of this package is calling functions from standard kite package. It should be same way if you standard zerodha package. 

standard zerodha package here .. https://github.com/zerodha/pykiteconnect

I copied those functions screenshots from here.

**Comment by akshatc12** [comment]
Interesting! I only have jugaad-trader installed. I don't have the official
kite at all, I am still able to use various other functions such as
"margins", "place_gtt", etc.

The only function I am unable to call is "order_margins".

Also, just like the official kiteconnect users can use the api_key and
create custom functions using the api document (
https://kite.trade/docs/connect/v3/margins/)

Can jugaad-trader users do the same?

**Comment by ssheikh098** [comment]
Without standard how can you call Jugaad trader? When you install jugaad trader the standard package installs automatically.

***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by sevakram** [comment]
@BruceWayne1219 , Please re-install `jugaad-trader` and report the issue if issue still persists
