### ISSUE TITLE
ModuleNotFoundError: No module named 'attrs' 

### ISSUE THREAD

**Issue by namang500** [jugaad-py/jugaad-trader#51]
**Describe the bug**
I am getting below error while executing $jtrader zerodha startsession  command

**Code snippet**
$jtrader zerodha startsession 

**Error**
<img width="780" alt="Screenshot 2023-01-23 at 2 29 14 PM" src="https://user-images.githubusercontent.com/14822528/214000511-e337aa07-cd50-49dc-9a2f-6f35da3649e8.png">

**Comment by hemangjoshi37a** [comment]
Please post the whole from your project and whole error to know what is causing the problem.

**Comment by sevakram** [comment]
No reply from the author hence closing, if issue persists, please open the ticket with more details..
