### ISSUE TITLE
What is the URL the code is hitting?

### ISSUE THREAD

**Issue by krishnak** [jugaad-py/jugaad-trader#53]
This is not really an issue but a clarification on how the code works to fetch historical data from Zerodha? From the code it appears to hit kite.zerodha.com or is the library built from a different source? but kite.zerodha.com doesn't support historical data when I try to access it. What is the api key that needs to be used for fetching historical data?

 I am trying to write a java version based on your code, I have successfully logged in, got the encryption key public key etc. But unable to fetch historical data as the API doesn't accept the api_key(I am using kitefront picked up from your code). From what I gather historical data is just via HTTP request, so the missing factor seems to be the URL and the api_key.

Could you throw some light.

**Comment by sevakram** [comment]
I have just inherited `Zerodha` class from `KiteConnect` class and overloaded the `_request` method.

Rest of the functionality is exactly same as `pykiteconnect`

**Comment by sevakram** [comment]
I checked code and I am not setting api_key explicitly but you can try `api_key="kitefront"` as I remember from top of my head
