### ISSUE TITLE
Not able to install jugaad-trader on windows using pip

### ISSUE THREAD

**Issue by arthbhalodiya** [jugaad-py/jugaad-trader#55]
**Describe the bug**
Getting Error while installing package using pip on windows

**Code snippet**
`pip install jugaad-trader`

**Error**
C:\Users\ArthBalodiya>pip install jugaad-trader
Collecting jugaad-trader
  Using cached jugaad_trader-0.18-py3-none-any.whl (11 kB)
Collecting requests==2.23.0 (from jugaad-trader)
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting websockets==8.1 (from jugaad-trader)
  Using cached websockets-8.1-cp312-cp312-win_amd64.whl
Collecting kiteconnect==3.8.2 (from jugaad-trader)
  Using cached kiteconnect-3.8.2.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting beautifulsoup4 (from jugaad-trader)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting Click==7.1.2 (from jugaad-trader)
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: six in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from jugaad-trader) (1.16.0)
Requirement already satisfied: pyOpenSSL>=17.5.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from kiteconnect==3.8.2->jugaad-trader) (23.3.0)
Collecting enum34>=1.1.6 (from kiteconnect==3.8.2->jugaad-trader)
  Using cached enum34-1.1.10-py3-none-any.whl (11 kB)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from kiteconnect==3.8.2->jugaad-trader) (2.8.2)
Requirement already satisfied: autobahn>=17.10.1 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (19.11.2)
Requirement already satisfied: pywin32 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from kiteconnect==3.8.2->jugaad-trader) (306)
Collecting chardet<4,>=3.0.2 (from requests==2.23.0->jugaad-trader)
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5 (from requests==2.23.0->jugaad-trader)
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.23.0->jugaad-trader)
  Using cached urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from requests==2.23.0->jugaad-trader) (2023.7.22)
Collecting soupsieve>1.2 (from beautifulsoup4->jugaad-trader)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: txaio>=18.8.1 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from autobahn>=17.10.1->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (23.1.1)
Requirement already satisfied: cryptography>=2.7 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from autobahn>=17.10.1->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (41.0.5)
Requirement already satisfied: zope.interface>=3.6.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (6.1)
Requirement already satisfied: Twisted>=12.1.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (23.10.0)
Requirement already satisfied: cffi>=1.12 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from cryptography>=2.7->autobahn>=17.10.1->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (1.16.0)
Requirement already satisfied: attrs>=21.3.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (23.1.0)
Requirement already satisfied: automat>=0.8.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (22.10.0)
Requirement already satisfied: constantly>=15.1 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (23.10.4)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (21.0.0)
Requirement already satisfied: incremental>=22.10.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (22.10.0)
Requirement already satisfied: twisted-iocpsupport<2,>=1.0.2 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (1.0.4)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from Twisted>=12.1.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (4.8.0)
Requirement already satisfied: setuptools in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from zope.interface>=3.6.0->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (68.2.2)
Requirement already satisfied: pycparser in c:\users\arthbalodiya\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.12->cryptography>=2.7->autobahn>=17.10.1->autobahn[twisted]>=17.10.1->kiteconnect==3.8.2->jugaad-trader) (2.21)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Building wheels for collected packages: kiteconnect
  Building wheel for kiteconnect (setup.py) ... done
  WARNING: Legacy build of wheel for 'kiteconnect' created no files.
  Command arguments: 'C:\Users\ArthBalodiya\AppData\Local\Programs\Python\Python312\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
   This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  
   - It imports setuptools before invoking setup.py, to enable projects that directly
     import from `distutils.core` to work with newer packaging standards.
   - It provides a clear error message when setuptools is not installed.
   - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
     setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
       manifest_maker: standard file '"'"'-c'"'"' not found".
   - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'C:\\Users\\ArthBalodiya\\AppData\\Local\\Temp\\pip-install-5ytn5nih\\kiteconnect_8ebc7e056cb54c589028e52658b79a30\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d 'C:\Users\ArthBalodiya\AppData\Local\Temp\pip-wheel-09as7xw9'
  Command output: [use --verbose to show]
  Running setup.py clean for kiteconnect
Failed to build kiteconnect
ERROR: Could not build wheels for kiteconnect, which is required to install pyproject.toml-based projects

**Comment by sevakram** [comment]
@arthbhalodiya , Can you please try now, we released a new version yesterday.

It says- `Failed to build kiteconnect` and `ERROR: Could not build wheels for kiteconnect, which is required to install pyproject.toml-based projects`

So problem looks to be with Zerodha's client `pykiteconnect` which is a dependency for `jugaad-trader`

Try installing `pip install build` first and then run `pip install jugaad-trader` 

If it still persists, try installing `kiteconnect` separately and raise an issue with pykiteconnect (https://github.com/zerodha/pykiteconnect)

**Comment by arthbhalodiya** [comment]
Yep, now it's working
Thanks!!!
