### ISSUE TITLE
How to solve "Bad Request" error in ltp and quote methods?

### ISSUE THREAD

**Issue by st271** [jugaad-py/jugaad-trader#62]
I a trying to solve this bug which is affecting the kite.ltp and kite.quote methods. I have followed this solution https://github.com/jugaad-py/jugaad-trader/issues/59#issuecomment-2141187407 but it didnt work because its only a partial solution. I have copy pasted all the methods shared in the post to Zerodha.py under "class Zerodha(KiteConnect)", I then modified 

```
def quote(self, kws, symb):
    ltp1 = None
    ltp1 = self.subscribe_instrument(kws, symb)
    print(self.last_price)
    print("I am here")
    self.unsubscribe(kws, symb)
    return ltp1
  ```
  
 to
   
```
def quote(self, symb):
        kws = self.ticker()
        ltp1 = None
        ltp1 = self.subscribe_instrument(kws, symb)
        print(self.last_price)
        print("I am here")
        self.unsubscribe(kws, symb)
        return ltp1
```

and called "kite.quote("NSE:INFY")"

but its giving this error

```
File ~/.venvs/venv/lib/python3.10/site-packages/jugaad_trader/zerodha.py:243, in Zerodha.subscribe_instrument(self, kws, instrument_token)
    241 def subscribe_instrument(self, kws, instrument_token):
    242     global instrument
--> 243     instrument = int(instrument_token)
    244     if kws.is_connected():
    245         kws.subscribe([instrument])

ValueError: invalid literal for int() with base 10: 'NSE:INFY'
```

**Comment by ssheikh098** [comment]
you need to pass instrument tokens of corresponding stock symbol instead of passing symbol itself. https://kite.trade/docs/connect/v3/market-quotes/#retrieving-the-full-instrument-list   eg - 408065 for NSE:INFY    https://kite.trade/docs/connect/v3/websocket/

**Comment by st271** [comment]
In pykiteconnect they have a **KiteConnect.quote()** method which by passing the list of symbols returns json output. Can we do that?
```
>>> kite.quote(['NSE:INFY'])
{u'NSE:INFY': {u'oi': 0, u'timestamp': 


datetime, u'net_change': 0}}

```

Last question: Why are we getting this error https://github.com/jugaad-py/jugaad-trader/issues/59, is it because zerodha is blocking those method calls or because this repo needs some bug fixes?

**Comment by st271** [comment]
@ssheikh098 

I have rerun this code with this option instrument token **12895746** but receiving **WebSocket is not connected.** error. This **kws.is_connected()** returns **False**. Any help would be appreciated

```
def quote(self, instrument_token):
        kws = self.ticker()
        ltp1 = None
        ltp1 = self.subscribe_instrument(kws, instrument_token)
        print("I am here")
        self.unsubscribe(kws, instrument_token)
        return ltp1
```
